"""notifications

Revision ID: 4ca0fe6231b1
Revises: 5241f67b3934
Create Date: 2026-09-27 15:14:04.268499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca0fe6231b1'
down_revision: Union[str, Sequence[str], None] = '5241f67b3934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.add_column('professional_profiles', sa.Column('notification_preferences', sa.String(), nullable=True))
    op.add_column('survivor_profiles', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('survivor_profiles', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('survivor_profiles', sa.Column('voice_language', sa.String(), nullable=True))
    op.add_column('survivor_profiles', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.add_column('survivor_profiles', sa.Column('notification_preferences', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survivor_profiles', 'notification_preferences')
    op.drop_column('survivor_profiles', 'profile_picture_url')
    op.drop_column('survivor_profiles', 'voice_language')
    op.drop_column('survivor_profiles', 'phone')
    op.drop_column('survivor_profiles', 'nickname')
    op.drop_column('professional_profiles', 'notification_preferences')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
