"""add_safety_plan

Revision ID: 5241f67b3934
Revises: 97af4cb89a8a
Create Date: 2026-09-27 14:57:21.745717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5241f67b3934'
down_revision: Union[str, Sequence[str], None] = '97af4cb89a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('warning_signs', sa.String(), nullable=True),
    sa.Column('coping_strategies', sa.String(), nullable=True),
    sa.Column('trusted_contacts', sa.String(), nullable=True),
    sa.Column('safe_places', sa.String(), nullable=True),
    sa.Column('reasons_to_reach_out', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_plans_id'), 'safety_plans', ['id'], unique=False)
    op.add_column('ai_analyses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('ai_analyses', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('ai_conversation_summaries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('ai_conversation_summaries', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('ai_conversations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('ai_conversations', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('appointments', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('baselines', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('baselines', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('cases', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('referrals', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('referrals', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'updated_at')
    op.drop_column('referrals', 'created_by')
    op.drop_column('referrals', 'updated_at')
    op.drop_column('cases', 'created_by')
    op.drop_column('cases', 'updated_at')
    op.drop_column('baselines', 'created_by')
    op.drop_column('baselines', 'updated_at')
    op.drop_column('appointments', 'created_by')
    op.drop_column('appointments', 'updated_at')
    op.drop_column('ai_conversations', 'created_by')
    op.drop_column('ai_conversations', 'updated_at')
    op.drop_column('ai_conversation_summaries', 'created_by')
    op.drop_column('ai_conversation_summaries', 'updated_at')
    op.drop_column('ai_analyses', 'created_by')
    op.drop_column('ai_analyses', 'updated_at')
    op.drop_index(op.f('ix_safety_plans_id'), table_name='safety_plans')
    op.drop_table('safety_plans')
    # ### end Alembic commands ###
