"""Add onboarding fields

Revision ID: c0f7993821a9
Revises: 4ca0fe6231b1
Create Date: 2026-09-27 16:17:59.308374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f7993821a9'
down_revision: Union[str, Sequence[str], None] = '4ca0fe6231b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survivor_profiles', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.add_column('survivor_profiles', sa.Column('consent_completed', sa.Boolean(), nullable=True))
    op.add_column('survivor_profiles', sa.Column('permissions_reviewed', sa.Boolean(), nullable=True))
    op.add_column('survivor_profiles', sa.Column('profile_completed', sa.Boolean(), nullable=True))
    op.add_column('survivor_profiles', sa.Column('check_in_streak', sa.Integer(), nullable=True))
    op.add_column('survivor_profiles', sa.Column('longest_streak', sa.Integer(), nullable=True))
    op.add_column('survivor_profiles', sa.Column('total_check_ins', sa.Integer(), nullable=True))
    op.add_column('survivor_profiles', sa.Column('last_check_in_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survivor_profiles', 'last_check_in_date')
    op.drop_column('survivor_profiles', 'total_check_ins')
    op.drop_column('survivor_profiles', 'longest_streak')
    op.drop_column('survivor_profiles', 'check_in_streak')
    op.drop_column('survivor_profiles', 'profile_completed')
    op.drop_column('survivor_profiles', 'permissions_reviewed')
    op.drop_column('survivor_profiles', 'consent_completed')
    op.drop_column('survivor_profiles', 'onboarding_completed')
    # ### end Alembic commands ###
